# Generated by Django 6.0.6 on 2026-06-15 18:13

from django.db import migrations

def seed_templates(apps, schema_editor):
    ResumeTemplate = apps.get_model('users', 'ResumeTemplate')
    
    templates = [
        {
            "name": "Harvard Resume",
            "category": "Academic / Classic",
            "description": "The traditional Harvard layout. Elegant serif style with uppercase section headers and horizontal separators. Best for academic, legal, and traditional corporate careers.",
            "preview_image": "classic",
            "latex_template": r"""\documentclass[11pt,a4paper]{article}
\usepackage[margin=0.75in]{geometry}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{hyperref}

\titleformat{\section}{\large\bfseries\uppercase}{}{0em}{}[\titrule]
\titlespacing{\section}{0pt}{12pt}{8pt}
\setlist[itemize]{leftmargin=0.2in, label={$\bullet$}, itemsep=0pt, parsep=2pt, topsep=2pt}

\begin{document}

\begin{center}
{\Huge \textbf{[[NAME]]}} \vspace{4pt} \\
[[EMAIL]] \quad|\quad [[PHONE]] \quad|\quad [[LINKEDIN]]
\end{center}

[[EXPERIENCE]]
[[EDUCATION]]
[[PROJECTS]]
[[SKILLS]]
[[CERTIFICATIONS]]
[[ADDITIONAL]]

\end{document}"""
        },
        {
            "name": "ATS Professional",
            "category": "Professional",
            "description": "A highly readable sans-serif template optimized specifically for parsing accuracy in Applicant Tracking Systems. Perfect for modern tech and business roles.",
            "preview_image": "professional",
            "latex_template": r"""\documentclass[10pt,a4paper]{article}
\usepackage[margin=0.65in]{geometry}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{hyperref}

\renewcommand{\familydefault}{\sfdefault}

\titleformat{\section}{\fontfamily{phv}\selectfont\large\bfseries}{}{0em}{}[\titrule]
\titlespacing{\section}{0pt}{10pt}{6pt}
\setlist[itemize]{leftmargin=0.18in, label={$\circ$}, itemsep=0pt, parsep=1.5pt, topsep=1.5pt}

\begin{document}

\noindent{\Huge \textbf{[[NAME]]}} \hfill [[EMAIL]] \\
[[PHONE]] \hfill [[LINKEDIN]]
\vspace{6pt}

[[EXPERIENCE]]
[[EDUCATION]]
[[PROJECTS]]
[[SKILLS]]
[[CERTIFICATIONS]]
[[ADDITIONAL]]

\end{document}"""
        },
        {
            "name": "Modern Minimal",
            "category": "Creative / Minimalist",
            "description": "An elegant, clean design with generous margins, asymmetric spacing, and a touch of deep color for a stylish presentation.",
            "preview_image": "minimalist",
            "latex_template": r"""\documentclass[11pt,a4paper]{article}
\usepackage[margin=0.8in]{geometry}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{hyperref}
\usepackage{color}

\definecolor{primary}{rgb}{0.1, 0.2, 0.4}
\titleformat{\section}{\large\bfseries\color{primary}}{}{0em}{}[\vspace{2pt}\hrule height 0.5pt]
\titlespacing{\section}{0pt}{14pt}{8pt}
\setlist[itemize]{leftmargin=0.22in, label={-}, itemsep=0.5pt, parsep=2pt, topsep=2pt}

\begin{document}

\noindent {\Huge \textbf{[[NAME]]}} \\
\noindent \textit{[[EMAIL]] $\cdot$ [[PHONE]] $\cdot$ [[LINKEDIN]]}
\vspace{10pt}

[[EXPERIENCE]]
[[EDUCATION]]
[[PROJECTS]]
[[SKILLS]]
[[CERTIFICATIONS]]
[[ADDITIONAL]]

\end{document}"""
        },
        {
            "name": "Software Engineer",
            "category": "Technical",
            "description": "Tailored for software developers and systems engineers. Places the technical skills inventory right at the top for immediate recruiter visibility.",
            "preview_image": "technical",
            "latex_template": r"""\documentclass[11pt,a4paper]{article}
\usepackage[margin=0.7in]{geometry}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{hyperref}

\renewcommand{\familydefault}{\sfdefault}
\titleformat{\section}{\large\bfseries\uppercase}{}{0em}{}[\titrule]
\titlespacing{\section}{0pt}{12pt}{8pt}
\setlist[itemize]{leftmargin=0.2in, label={$\bullet$}, itemsep=0pt, parsep=2pt, topsep=2pt}

\begin{document}

\begin{center}
{\Huge \textbf{[[NAME]]}} \\
\href{mailto:[[EMAIL]]}{[[EMAIL]]} $\cdot$ [[PHONE]] $\cdot$ \href{https://[[LINKEDIN]]}{[[LINKEDIN]]}
\end{center}
\vspace{-6pt}

[[SKILLS]]
[[EXPERIENCE]]
[[PROJECTS]]
[[EDUCATION]]
[[CERTIFICATIONS]]
[[ADDITIONAL]]

\end{document}"""
        },
        {
            "name": "Data Scientist",
            "category": "Technical",
            "description": "Optimized for quantitative roles (Data Analyst, ML Engineer, Researcher). Emphasizes core algorithms, tools, projects, and impact metrics.",
            "preview_image": "analytical",
            "latex_template": r"""\documentclass[11pt,a4paper]{article}
\usepackage[margin=0.7in]{geometry}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{hyperref}
\usepackage{color}

\definecolor{darkblue}{rgb}{0.0, 0.2, 0.5}
\titleformat{\section}{\large\bfseries\color{darkblue}\uppercase}{}{0em}{}[\titrule]
\titlespacing{\section}{0pt}{12pt}{8pt}
\setlist[itemize]{leftmargin=0.2in, label={$\blacktriangleright$}, itemsep=0.5pt, parsep=2pt, topsep=2pt}

\begin{document}

\begin{center}
{\Huge \textbf{[[NAME]]}} \\
[[EMAIL]] $\cdot$ [[PHONE]] $\cdot$ [[LINKEDIN]]
\end{center}
\vspace{-4pt}

[[SKILLS]]
[[PROJECTS]]
[[EXPERIENCE]]
[[EDUCATION]]
[[CERTIFICATIONS]]
[[ADDITIONAL]]

\end{document}"""
        }
    ]
    
    for t in templates:
        ResumeTemplate.objects.get_or_create(
            name=t["name"],
            defaults={
                "category": t["category"],
                "description": t["description"],
                "preview_image": t["preview_image"],
                "latex_template": t["latex_template"],
                "is_public": True
            }
        )

def remove_templates(apps, schema_editor):
    ResumeTemplate = apps.get_model('users', 'ResumeTemplate')
    ResumeTemplate.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resumetemplate_usertemplate'),
    ]

    operations = [
        migrations.RunPython(seed_templates, reverse_code=remove_templates),
    ]

